"""Add new table 'companies' 

Revision ID: 7c62893038eb
Revises: 8a588c450708
Create Date: 2022-04-28 15:31:36.222261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c62893038eb'
down_revision = '8a588c450708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employers', sa.Column('company_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'employers', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.drop_column('employers', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
