"""Add new field.

Revision ID: 8a588c450708
Revises: 298e06cdea4b
Create Date: 2022-04-23 11:29:13.575614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a588c450708'
down_revision = '298e06cdea4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('work_as', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'work_as')
    # ### end Alembic commands ###
